Added bash directory scripts

diff --git a/shell/bashrc.erb b/shell/bashrc.erb
--- a/shell/bashrc.erb
+++ b/shell/bashrc.erb
@@ -1,80 +1,103 @@
-eval "$(pyenv init -)"
+# Make sure the shell is interactive
+case $- in
+    *i*) ;;
+    *) return ;;
+esac
 
-# Disable bash history
-export HISTFILE=/dev/null
+# Don't do anything if restricted, not even sourcing the ENV file; testing
+# whether $- contains 'r' doesn't work, because Bash doesn't set that flag
+# until after .bashrc has evaluated
+! shopt -q restricted_shell 2>/dev/null || return
 
-# c = clear
-alias c='clear'
+# Clear away all aliases; we do this here rather than in the $ENV file shared
+# between POSIX shells, because ksh relies on aliases to implement certain
+# POSIX utilities, like fc(1) and type(1)
+unalias -a
 
-# Colorize ls
-alias ls='ls -ltra'
+# If ENV is set, source it to get all the POSIX-compatible interactive stuff;
+# we should be able to do this even if we're running a truly ancient Bash
+if [ -n "$ENV" ] ; then
+    . "$ENV"
+fi
 
-# Directory movements
-alias ..='cd ..'
+# Ensure we're using at least version 3.0
+# shellcheck disable=SC2128
+[ -n "$BASH_VERSINFO" ] || return    # Check version array exists (>=2.0)
+((BASH_VERSINFO[0] >= 3)) || return  # Check actual major version number
 
-# Prefer vim
-alias vi=vim
-alias edit='vim'
+# Clear away command_not_found_handle if a system bashrc file set it up
+unset -f command_not_found_handle
 
-# Show open ports
-alias ports='netstat -tulan'
+# Keep around 32K lines of history in file
+HISTFILESIZE=$((1 << 15))
 
-# Hard drive health
-alias df='df -H'
+# Ignore duplicate commands
+HISTCONTROL=ignoredups
 
-# Reload .bashrc file
-alias r='bashrc-reload() { builtin exec bash ; }'
+# Keep the times of the commands in history
+HISTTIMEFORMAT='%F %T  '
 
-# Server the current directory
-alias serve='python -m SimpleHTTPServer'
+# Use a more compact format for the `time` builtin's output
+TIMEFORMAT='real:%lR user:%lU sys:%lS'
 
-# Mounts in a decent format
-alias m='mount | column -t'
+# Correct small errors in directory names given to the `cd` builtin
+shopt -s cdspell
+# Check that hashed commands still exist before running them
+shopt -s checkhash
+# Update LINES and COLUMNS after each command if necessary
+shopt -s checkwinsize
+# Put multi-line commands into one history entry
+shopt -s cmdhist
+# Include filenames with leading dots in pattern matching
+shopt -s dotglob
+# Enable extended globbing: !(foo), ?(bar|baz)...
+shopt -s extglob
+# Append history to $HISTFILE rather than overwriting it
+shopt -s histappend
+# If history expansion fails, reload the command to try again
+shopt -s histreedit
+# Load history expansion result as the next command, don't run them directly
+shopt -s histverify
+# Don't assume a word with a @ in it is a hostname
+shopt -u hostcomplete
+# Don't change newlines to semicolons in history
+shopt -s lithist
+# Don't try to tell me when my mail is read
+shopt -u mailwarn
+# Don't complete a Tab press on an empty line with every possible command
+shopt -s no_empty_cmd_completion
+# Use programmable completion, if available
+shopt -s progcomp
+# Warn me if I try to shift nonexistent values off an array
+shopt -s shift_verbose
+# Don't search $PATH to find files for the `source` builtin
+shopt -u sourcepath
 
-# Get current IP address
-alias ip='curl ifconfig.me'
+# These options only exist since Bash 4.0-alpha
+if ((BASH_VERSINFO[0] >= 4)) ; then
 
-# Close shell and keep subprocesses alive
-alias e='disown -a && exit'
+    # Correct small errors in directory names during completion
+    shopt -s dirspell
+    # Allow double-star globs to match files and recursive paths
+    shopt -s globstar
 
-# ASCII table
-alias a='man ascii'
-
-alias r='reset'
-
-# Open finder in the current terminal location
-alias o='open .'
-
-# Papertrail alias courtesy of https://github.com/papertrail/papertrail-cli README.md file
-alias pt=papertrail
-
-# AWS Login
-alias awslogin='aws-vault login mozilla-itsre-admin'
-
-# AWS Debugging
-alias awsinitproject='sam init --runtime python3.7'
-
-# AWS Environment Dump
-alias awsenv='env | grep AWS'
-
-function aws-vault() {
-    local aws_vault_cmd=$(which aws-vault)
- 
-    if [ -z "${aws_vault_cmd}" ]; then
-        echo "aws-vault is not on your path you do not have it installed"
-        exit 1
+    # Warn me about stopped jobs when exiting
+    # Available since 4.0, but only set it if >=4.1 due to bug:
+    # <https://lists.gnu.org/archive/html/bug-bash/2009-02/msg00176.html>
+    if ((BASH_VERSINFO[1] >= 1)) ; then
+        shopt -s checkjobs
     fi
-    case "$1" in
-        exec)
-            local action=$1
-            shift 1
-            local profile=$1
-            shift 1
-            local options="--assume-role-ttl=1h --session-ttl=4h"
-            ${aws_vault_cmd} ${action} ${profile} ${options} $@
-        ;;
-        *)
-            ${aws_vault_cmd} $@
-        ;;
-    esac
-}
+
+    # Expand variables in directory completion
+    # Only available since 4.3
+    if ((BASH_VERSINFO[1] >= 3)) ; then
+        shopt -s direxpand
+    fi
+fi
+
+# Load Bash-specific startup files
+for bash in "$HOME"/.bashrc.d/*.bash ; do
+    [[ -e $bash ]] || continue
+    source "$bash"
+done
+unset -v bash
